# Generated by Django 3.1.1 on 2021-12-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Github',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(default='', max_length=100)),
                ('device_code', models.CharField(default='', max_length=100)),
                ('access_token', models.CharField(default='', max_length=100)),
                ('scope', models.CharField(choices=[('ALL', 'repo')], default='repo', max_length=20)),
            ],
        ),
    ]
