# Generated by Django 3.1.1 on 2021-12-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='github',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='github',
            name='client_secret',
            field=models.CharField(default='', max_length=100),
        ),
    ]
