# Generated by Django 3.1.1 on 2021-12-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0002_auto_20211208_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='github',
            name='main_repository',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='github',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
